// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMOP1_bATRP3saCaFD47Z0Y2vCGfjz_Gc',
    appId: '1:1037949925427:web:a82cf1070fbe663b90cb46',
    messagingSenderId: '1037949925427',
    projectId: 'utsmobile-ec6c2',
    authDomain: 'utsmobile-ec6c2.firebaseapp.com',
    storageBucket: 'utsmobile-ec6c2.appspot.com',
    measurementId: 'G-TTK2XCNHP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LoMSKyhh9oT72kULk_WQMgCsuniuMdo',
    appId: '1:1037949925427:android:835a2e8832a539a490cb46',
    messagingSenderId: '1037949925427',
    projectId: 'utsmobile-ec6c2',
    storageBucket: 'utsmobile-ec6c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOnXGz-pGTWiio-c9UHfa_OwbpW5pHak',
    appId: '1:1037949925427:ios:0b7a47122fdaf42590cb46',
    messagingSenderId: '1037949925427',
    projectId: 'utsmobile-ec6c2',
    storageBucket: 'utsmobile-ec6c2.appspot.com',
    iosClientId: '1037949925427-7n86he4d1um6d7cfj8vdq5u1ce8pdpkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOnXGz-pGTWiio-c9UHfa_OwbpW5pHak',
    appId: '1:1037949925427:ios:afce6bb9edf0d36590cb46',
    messagingSenderId: '1037949925427',
    projectId: 'utsmobile-ec6c2',
    storageBucket: 'utsmobile-ec6c2.appspot.com',
    iosClientId: '1037949925427-pfptffojd9d2d975toa3ptm5n5dgb9em.apps.googleusercontent.com',
    iosBundleId: 'com.example.utsmobile.RunnerTests',
  );
}
